name: "setup KVM"
description: "setup KVM group for Android Emulator"
inputs:
  prepare-script:
    description: "custom script to run before the main script - e.g. `./gradlew assembleDebugAndroidTest`"
    required: false
  script:
    description: "custom script to run - e.g. `./gradlew connectedDebugAndroidTest`"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: setup KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: 'avd-${{ runner.os }}-${{ inputs.script }}-${{ inputs.prepare-script }}'

    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: prepare script
      shell: bash
      if: inputs.prepare-script != ''
      run: |
        ${{ inputs.prepare-script }}

    - name: run script
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ${{ inputs.script }}
