# $schema: https://json.schemastore.org/github-action.json
name: "setup gradle"
description: "ditto"
inputs:
  cache-encryption-key:
    description: "use `secrets.GRADLE_ENCRYPTION_KEY` via `openssl rand -base64 16`"
    required: true
runs:
  using: "composite"
  steps:
    - name: setup gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        gradle-version: wrapper
        cache-cleanup: always
        artifact-retention-days: 3
        cache-encryption-key: ${{ inputs.cache-encryption-key }}

    - name: list toolchain
      shell: bash
      run: |
        ./gradlew -q javaToolchains
