name: check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflows }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - uses: reviewdog/action-setup@v1
      - name: run android lint
        shell: bash
        run: |
          ./gradlew :app:lintDebug
      - name: run detekt
        shell: bash
        run: |
          ./gradlew detekt
      - name: run reviewdog review
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat app/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="android lint" -reporter=github-pr-review;
          cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter=github-pr-review;
      - name: run reviewdog suggest
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew lintFix --continue;
          ./gradlew detekt -PautoCorrect --continue;
          TMPFILE=$(mktemp);
          git diff >"${TMPFILE}";
          git stash -u || git stash drop;
          cat "${TMPFILE}" | reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review;

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: unit test
        shell: bash
        run: |
          ./gradlew testDebugUnitTest
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          check_name: unit-test-result
          files: |
            **/test-results/**/*.xml

  android-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - uses: ./.github/actions/avd
        with:
          prepare-script: ./gradlew assembleDebug
          script: ./gradlew connectedDebugAndroidTest
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          check_name: android-test-result
          files: |
            **/outputs/androidTest-results/connected/**/*.xml
